#server.port=${port:8081}
server:
  port: 8081
#spring.data.mongodb.uri=mongodb://${db:carts-db}:27017/data
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: carts
  data:
    mongodb:
      uri: mongodb://localhost:27017/data
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 39.104.112.98:8848
#spring.zipkin.baseUrl=http://${zipkin_host:zipkin}:9411/
#spring.zipkin.enabled=${zipkin_enabled:false}
#spring.cloud.nacos.discovery.server-addr=39.104.112.98:8848
#spring.cloud.nacos.discovery.username=nacos
#spring.cloud.nacos.discovery.password=nacos
# Disable actuator metrics endpoints
#management.endpoint.metrics.enabled=false
#endpoints.prometheus.id=metrics
